LOCAL:
    temp-directory:
    memory: 4g
META:
    species:
        - SPECIES_ONE
        - SPECIES_TWO
    ratio: 0.2
    reference-file:
    annotation-file:
    reference-directory:
FILTER:
    5-prime-smart-adapter: 
    cell-barcode:
        start:
        end:
    UMI-barcode:
        start:
        end:
    cutadapt:
        adapters-file:
        R1:
            quality-filter: 20
            maximum-Ns: 0
            extra-params: ''
        R2:
            quality-filter: 20
            minimum-adapters-overlap: 6
            minimum-length: 15
            extra-params: ''
MAPPING:
    STAR:
        genomeChrBinNbits: 18
        outFilterMismatchNmax: 10
        outFilterMismatchNoverLmax: 0.3
        outFilterMismatchNoverReadLmax: 1
        outFilterMatchNmin: 0
        outFilterMatchNminOverLread: 0.66
        outFilterScoreMinOverLread: 0.66
EXTRACTION:
    UMI-edit-distance:
    minimum-counts-per-UMI: